#!/bin/bash

echo "🚀 QuakeSense Mobile App - Build Commands"
echo "=========================================="
echo ""
echo "📦 Before building, make sure you:"
echo "  1. Have Expo CLI installed: npm install -g eas-cli"
echo "  2. Are logged in to Expo: eas login"
echo "  3. Have EAS project configured: eas init"
echo ""
echo "📱 BUILD OPTIONS:"
echo ""
echo "1️⃣  Development APK (fast, for testing):"
echo "   eas build --platform android --build-type apk"
echo ""
echo "2️⃣  Production APK (for manual testing):"
echo "   eas build --platform android --build-type apk --profile production"
echo ""
echo "3️⃣  AAB for Google Play (recommended):"
echo "   eas build --platform android --profile production"
echo ""
echo "4️⃣  iOS Build:"
echo "   eas build --platform ios --profile production"
echo ""
echo "5️⃣  Preview Build (internal testing):"
echo "   eas build --platform android --profile preview"
echo ""
echo "6️⃣  Watch Build Progress:"
echo "   eas build:list"
echo ""
echo "7️⃣  Submit to Play Store:"
echo "   eas submit --platform android --latest"
echo ""
echo "8️⃣  Submit to App Store:"
echo "   eas submit --platform ios --latest"
echo ""
echo "✅ If you haven't initialized EAS yet:"
echo "   cd mobile && eas init --id com.quakesense"
echo ""
echo "🎯 QUICK START:"
echo "   cd mobile"
echo "   eas build --platform android --build-type apk"
